name: epgmytvsuper

# 每小时执行一次
on:
  schedule:
    - cron: '35 */23 * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 PHP 7.4 环境
      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # 第三步：运行 epgmytvsuper.php，生成 epgmytvsuper.xml
      - name: Run epgmytvsuper.php
        run: |
          php epgmytvsuper.php  # 运行生成 epgmytvsuper.xml 的 PHP 脚本

      # 第四步：上传文件到 epgtest2 仓库
      - name: Upload epgmytvsuper.xml to epgtest2
        uses: actions/upload-artifact@v4
        with:
          name: epgmytvsuper.xml
          path: epgmytvsuper.xml

      # 第五步：下载到目标仓库并覆盖文件
      - name: Checkout epgtest2 repository
        uses: actions/checkout@v4
        with:
          repository: zzq1234567890/epgtest2  # 目标仓库
          token: ${{ secrets.GITHUB_TOKEN }}
          path: epgtest2  # 克隆到本地的路径

      # 第六步：检查 epgmytvsuper.xml 是否存在并被修改
      - name: Check if epgmytvsuper.xml exists and is modified
        run: |
          if [ ! -f epgmytvsuper.xml ]; then
            echo "epgmytvsuper.xml does not exist."
            exit 1
          fi
          # 对比文件差异
          diff epgtest2/epgmytvsuper.xml epgmytvsuper.xml || echo "File is modified"
  
      # 第七步：将 epgmytvsuper.xml 覆盖上传到 epgtest2
      
      - name: Replace epgmytvsuper.xml and push
        run: |
          mv epgmytvsuper.xml epgtest2/epgmytvsuper.xml  # Move the file to target directory
           cd epgtest2
            git config --global user.name "zzq1234567890"
            git config --global user.email "zhangzhenqiu@foxmail.com"
            git add epgmytvsuper.xml
            git stash push -m "Stashing uncommitted changes before pull"
            git pull origin main --rebas
            git stash pop
            git commit -m "Update epgmytvsuper.xml" --allow-empty  # Force commit if no actual changes
            git push origin main

          
